### ISSUE TITLE
IAL 1 Update - Low assurance identity proofing and enrolment

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#1]
In SP 800-63A rev. 4, NIST is considering an update to IAL1 to provide processes for low assurance identity proofing and enrolment. This is intended to support federal agency low risk and low impact transactions and services. NIST is considering the following processes for this update to IAL1:

- Acceptance of self-asserted attributes as identity evidence, as well as documentary evidence, for identity resolution and validation;
- Validation of self-asserted attributes, as well as documentary evidence, against federal agency records or other available sources;
- Verification of the binding of validated identity evidence, self-asserted and documentary, to the applicant, through:
    - Physical or biometric comparison,
    - the use of knowledge-based verification (KBV) in accordance with SP 800-63A section 5.3.2, 
    - verification of an enrolment code sent to the validated address (postal, email, PSTN/SMS) of the applicant. 

The selection of updated IAL1 identity proofing would reflect low risks and low impacts of identity proofing errors to the online service, in particular proofing errors that would provide access to the online service to wrong subject (e.g., an attacker successfully proofs as  someone else). NIST is interested in input to the processes described above and descriptions of specific federal agency use cases that would be applicable for this level of identity proofing.

**Comment by Treeced** [comment]
With these proposals, would the new IAL1 preclude the anonymous use case?  As an example, whistleblowers or medical research that could require strong authentication but not be identified.  How would these cases be handled within the propose changes? Thanks

**Comment by jimfenton** [comment]
The anonymous use case is important, and will not be precluded by this new definition of IAL1. It will still be possible to enroll without identity proofing -- "without IAL", if you will. The CSP simply will not associate an IAL with the account.

**Comment by JayMMeier** [comment]
"Biometric comparison" may need definition.  Would Liveness and biometric matching data be required?  Would the biometric data be bound to any specific user identity data or profile data?  Or simply to a device, which does not bind the biometric to any actual identity data?

**Comment by Homebush** [comment]
Just a point of clarification if that's OK.. 
Those bullets are drafted to describe 'or', not 'and', correct?
"Verification of the binding of validated identity evidence, self-asserted and documentary, to the applicant, through:
- Physical or biometric comparison, _**or**_
- the use of knowledge-based verification (KBV) in accordance with SP 800-63A section 5.3.2, **_or_**
- verification of an enrolment code sent to the validated address (postal, email, PSTN/SMS) of the applicant.

**Comment by jimfenton** [comment]
@JayMMeier :

In the context of identity proofing, biometric comparison refers to the matching of a biometric characteristic of the applicant to information on the identity evidence provided (not simply to a device).

Liveness detection requirements for remote identity proofing are addressed in #2.

**Comment by juliemaas** [comment]
Is the idea that a level IAL1.5 might be identified? It seems that since IAL1 is presently considered self-asserted/without verification that adding some steps to enrich it might be well communicated by a new level between 1 and 2.

What comes to mind as a use case for health care that might improve patient matching and be less challenging to meet than IAL2 is something like: 1 Fair (at least) photo ID, in the best case confirming photo match to subject, name, address and DOB, and verifying control of an email address or telephone number (i.e. not that the account is billed to the person's name).

**Comment by jimfenton** [comment]
@Homebush:

At this point, NIST is trying to understand the use cases for a redesigned AAL1, and set the identity proofing requirements accordingly. The three verification methods listed are candidates for methods that might be accepted under AAL1, and it has not been decided whether those methods would be used singly or in some combination.

**Comment by jimfenton** [comment]
@juliemaas Indeed, the disclosure of personal information through the use of KBV is but one of the problems with this technique (although the questions do not necessarily need to be multiple choice).

Do you have examples of use cases that would make use of what you're calling IAL 1.5? It doesn't make sense to define a level without a requirement that it be used somewhere.

**Comment by juliemaas** [comment]
@jimfenton I suggested IAL1.5 expecting it would be useful for patient registration, check-in, and portal credentials generation. The IAL1.5 process I describe is similar to what I'm aware many healthcare facilities already perform and inclusion of an email address or mobile number at the time of identity verification, as you know, provides a path to re-gaining access to the account or establishing the digital credentials in the first place so it would be helpful to round out a stronger nominal identity proofing requirement and would improve the state of patient access to their own data by collecting contact information during the proofing event. To create a bar that the industry can follow collectively would be helpful since to date the level needed has been more ambiguous, and meeting IAL2 seems daunting until REAL IDs are ubiquitous and anyone not eligible to receive one has an alternative Superior piece of evidence. Additionally, some health systems do mail (US Mail) notice or an enrollment code to the individual as part of this process and it seems helpful to health equity and patient information access in general to not require this as a baseline for online access to one's own health data.

In the remote version of this level IAL1.5, "selfie proofing" (photo compare with ID as per 800-63-3) wouldn't be required and instead simpler tech like uploading a photo of driver's license would be possible. As I recall from their respective websites this is what California requires to obtain immunization records; New Hampshire steps it up a little to require photo comparison by notary or provider. PayPal verifies using a [bank or credit card account](https://www.paypal.com/uk/smarthelp/article/how-do-i-verify-my-paypal-account-faq444) and in some circumstances [goes beyond that](https://www.paypal.com/us/smarthelp/article/what-kind-of-documentation-can-i-provide-to-prove-my-identity-faq3756). Naturally non-photo-ID items such as a birth certificate + utility bill (two Fairs) may be deemed equivalent. 

The reason to add mention of IAL1.8 would be if IAL1.5 patient IDs, valuable for improving patient matching, aren't being trusted for access to my health data wherever it may be (using my credential from my Epic practice to register as a new patient or access my data within a different patient portal, or to access any data--about myself only--in a broadcast query). The inclusion of what I refer to as IAL1.8 in TEFCA implies that it is thought to be sufficient for that purpose. Additionally, since full IAL2 is deemed necessary for access to health data queries about _any_ individual (not just me) in a network context and for administrators of those accounts, there is a need to differentiate between IAL1.8 (photo ID plus one Fair) and IAL2 (one Strong and two Fairs). You can see from those examples that the evidence differences between IAL1.8 and IAL2 are noteworthy.

**Comment by aviars** [comment]
This is an interesting topic and one I've also been noodling.   I think we need to list all of the "not quite IAL2 but something" items we can think of.  If NIST bundles these within IAL1 (in revision ) then maybe a 1.5 isn't needed at all?  I generally don't like the idea of adding a decimal. It feels messy, but this conversation exists for a reason.   It is a bit like interstates when letters are added exists as things get more complex.  What about a zero? 0,1,2,3?  

I drafted this on `IAL 1.5` before I saw this thread https://github.com/TransparentHealth/healthcare-trustmark/blob/main/ial-1-5-definition.md, but its sort of a moot point if  this proposal moves forward.  Having thought about it a while, I like the idea of updating IAL 1 and disposing of the IAL 1.5, 1.8, notions.  I think a zero would also be helpful.   These other details of IAL could/should be expressed in other less codified ways such as https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html

On another note, if SP 800-63 is going to be updated, it should include more about address/postal validation...in particular around utility bills and certificate signing.  See   https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html#name-utility_bill and https://openid.net/specs/openid-connect-4-identity-assurance-1_0.html#section-5.1.1.3 
More on this on another thread.  /cc  @jimfenton @juliemaas  @jricher

**Comment by KantaraInitiative-IAWG** [comment]
To support this concept, we have provided examples of how the existing tables in 800-63-3 and 800-63A could be updated to reflect the incremental assurance level between with areas highlighted that reflect difference from IAL2.  Kantara notes that the addition of the level it is recommending provides for the use of Fair Evidence which, up to this point, has not been used.
Please see the tables on the attached document.

Kantara would suggest that the name of this new level not be associated with another level.  That is, it not be labeled “1 Enhanced” or “2 Light”.  Labeling it “1 Enhanced” could make users think that it is, in essence, Level 1.  While labeling it “2 Light”, could diminish Level 2.  That being said, Kantara understands that labeling could be a challenge to those who have already been approved as meeting the requirements of an existing level.


[IAL 1 Update - Kantara comments.docx](https://github.com/usnistgov/800-63-4/files/6481053/IAL.1.Update.-.Kantara.comments.docx)

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.

**Comment by aviars** [comment]
@jricher and/or @jimfenton Can you share an estimated timeline for when NIST will publish a draft of revision 4 in the future?  

Thank you :-)

**Comment by jimfenton** [comment]
@aviars Please see: https://www.nist.gov/identity-access-management/roadmap-nist-special-publication-800-63-3-digital-identity-guidelines

**Comment by aviars** [comment]
Thanks @jimfenton   I see right now its projected for Q1 2022.

**Comment by aviars** [comment]
Any update on a publication date for revision 4?

**Comment by aviars** [comment]
I suggest NIST IAL definitions add an IAL of 0 (same as unknown) and lump "low-assurance" ID proofing into IAL 1.
