### ISSUE TITLE
Liveness test for remote identity proofing

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#2]
The goal of identity verification is to confirm and establish a linkage between the validated evidence for the claimed identity and the real-life applicant presenting the evidence.  During remote identity proofing this linkage is achieved through a physical or automated biometric comparison of the facial image (i.e., photograph) on the strongest piece of evidence to the applicant or by a biometric comparison between information on the evidence and a biometric characteristic obtained from the applicant.  NIST recognizes the growing threat to this process by biometric spoofing attacks and that liveness testing and other presentation attack detection technologies are emerging as the primary tools against these types of attacks. 
 
As such, we are considering new requirements and guidance on the use of these technologies in the identity proofing process, particularly in fully remote and supervised remote proofing scenarios.  We are seeking feedback on the following:

- The level of risk and/or types of threats associated with biometric spoofing in current remote identity proofing processes;
- Liveness or other presentation attack detection approaches currently supported by identity proofing services and technology providers;
- Relevant standards and testing/certification programs for these types of technologies; and
- The impact of liveness detection or other presentation attack detection capabilities on cost, usability, and market availability.

**Comment by Jay-SageCapAdv** [comment]
Thanks for this.  Lacking proper evaluation methods and test beds, NIST hasn't seemed able to address modern threat vectors, leaving FIPS201/PIV and related systems completely vulnerable. 

We have anticipated this discussion and will participate significantly.  

For an initial reference, we recommend reviewing www.liveness.com and www.spoofbounty.com .  

We will list numerous New Issues we believe are relevant.

**Comment by jricher** [comment]
"Biometric comparison" may need definition.  Would Liveness and biometric matching data be required?  Would the biometric data be bound to any specific user identity data or profile data?  Or simply to a device, which does not bind the biometric to any actual identity data?

_Originally posted by @JayMMeier in https://github.com/usnistgov/800-63-4/issues/1#issuecomment-814129045_

**Comment by JayMMeier** [comment]
### **Threats against today’s remote identity proofing processes:**
**Presentation Attacks** performed by a bad actor showing a mask, mannequin, video, digital, or paper photo (synthetic artifact) in place of a real, 3D human’s face. These attacks can affect initial Identity Verification and future Authentication sessions. Presentation Attacks are among the easiest to attempt and are pervasive, with an estimated 2% of all current Remote ID Verification attempts being PAD attacks. While often simple to procure and perform, Presentation Attacks can be very difficult to detect and are considered Levels 1-3 on the Liveness.com Attack Vector Scale.
**Biometric Template Tampering Attacks** are performed either on the device,  where the biometric data of the subject is replaced in the legitimate user data with imposter data before being matched against trusted data, or “man-in-the-middle” attacks, where the payload is intercepted and replaced in transit to the server. These attacks are considered Level 4 on the Liveness.com Attack Vector Scale.
**Camera Bypass Attacks** include processes whereby the bad actor bypasses the camera hardware and injects previously collected data into the video feed. Common Bypass techniques include using virtual camera software (e.g., ManyCam) or leveraging vulnerabilities in WebRTC by setting injection points or running the application on an emulator. These attacks are considered Level 5 on the Liveness.com Attack Vector Scale.
**"Imposter" Attacks** are perpetrated by presenting a live human to the camera who looks similar to the legitimate user. These attacks are more often successful against 2D or otherwise weak matching algorithms incapable of compensating for image capture perspective distortions. 2D “Selfie-to-ID Card” systems are particularly vulnerable to perspective distortions and result in lower match confidence. Lastly, 2D matching technologies or techniques that rely on collecting visible light are inherently less accurate when authenticating dark-skinned users, young users, and female users, while 3D systems, not relying on light, are not.  
**  -  Remote Identity Proofing and Authentication systems relying on biometric matching on a mobile device (like Apple and FIDO) are vulnerable to Imposter Attacks for several reasons.  First, the enrolled biometric data, on the device, is anonymous and cannot be bound to a Subscriber Account.  Second, the enrolled data cannot be moved from the device to a server, limiting match data size to accommodate fixed and limited in-device processing capability, impacting potential accuracy.  Further, in-device biometric processors do not provide any opportunity to scan for duplicate or fraudulent identity profiles (i.e., “de-dup”) within an identity profile database.  In-device biometric sensors are particularly vulnerable to Level 1-5 attacks on the Liveness.com Attack Vector Scale. 
[NIST_800-63_RFI_FaceTec_Reply.pdf](https://github.com/usnistgov/800-63-4/files/6312209/NIST_800-63_RFI_FaceTec_Reply.pdf)

**Comment by JayMMeier** [comment]
### Liveness methods in use by identity proofing and technology providers:
**Active Liveness Detection** commands the user to successfully perform a movement or action like blinking, smiling, tilting the head, and track-following a bouncing image on the device screen. Importantly, instructions must be randomized and the camera/system must observe the user perform the required action. 
**Passive Liveness** relies on involuntary user cues like pupil dilation, reducing user friction and session abandonment. Passive liveness can be undisclosed, randomizing attack vector approaches.  Alone, it can determine if captured image data is first-generation and not a replica presentation attack.  Moreover, within specific system architectures it can determine if the user is present in real-time, eliminating Levels 4-5 Attacks like video injection and others.
**Device & Server-Side Liveness** - Significantly higher Liveness and biometric match confidence can be gained if device camera data is captured securely with a verified camera feed, and the image data is verified to be captured in real-time by a device SDK.  Under these circumstances both Liveness and Match confidence can be determined concurrently from the same data, mitigating vulnerabilities.
**Multimodal Liveness** utilizes numerous weak Liveness modalites to establish user choice and increase the number of devices supported . This often requires the user to “jump through hoops'' of numerous Active Liveness tests, and increases friction.
**Liveness and 3D Depth Data Dependence** - A human must be 3D to be alive, while a mask-style artifact may be 3D without being alive. Thus, while 3D face depth measurements alone do not prove the subject is a live human, verifying 2-dimensionality proves the subject is not alive. Regardless of camera resolution, 3-dimensionality provides substantially more usable and consistent data than 2D, dramatically increasing accuracy. 3D depth detection is a critical component of stronger Liveness Detection, and in general, deleting used Liveness data is an effective means of mitigating Honeypot risk.  
 
**Specialized In-Device 3D Camera Hardware** (i.e., Apple's Face ID) can collect 3D Face Data almost instantaneously by projecting invisible dots on the face and analyzing derived depth data. However, it requires special hardware but provides much higher accuracy than legacy 2D Matching. 


**3D Face Data Collection Software** utilizes video frame data captured from the X & Y axes from numerous 2D video frames over a few seconds and processes observed changes in the facial appearance to "reverse-engineer" the 3D Face. 3D Face Liveness software systems are capable of securely delivering interdependent, concurrent Liveness and biometric data to a server for authentication against the Subscriber Account, and other subscriber accounts (1:N) for de-duplication and other anti-fraud tactics.  
[NIST_800-63_RFI_FaceTec_Reply.pdf](https://github.com/usnistgov/800-63-4/files/6312247/NIST_800-63_RFI_FaceTec_Reply.pdf)

**Comment by JayMMeier** [comment]
### Relevant standards and testing/certification programs for these types of technologies: 
**ENISA Remote ID Proofing Report** - Published: March 2021 - "1. During the identity verification session, the "liveness" of the applicant's facial image is verified. Presentation attack detection (PAD) and face matching controls are used. Technology addresses various presentation attacks (e.g. still or video imagery submission, usage of high-quality masks, replay of a previous video capture). The system is continually monitored and reacts to evolving threats. Face matching algorithm uses the latest advances in deep neural networks to deliver matching performance with the highest level of assurance. It is optimized for 'selfies' taken on smartphones and PCs in a huge variety of lighting conditions, poses, and facial features."
**ETSI "Survey of technologies and regulatory requirements for identity proofing"** Published: March 2021 - “...the applicant to take and send a mobile phone video or photo with other liveness checks; compare the applicant's submitted photo to the photos on the passport identity evidence or the photo on file in the government's passport or license database;”
**Liveness.com** - Published: September 2020 - Threat Vector Scale: PAD Levels 1-3, Level 4 = Payload Tampering Prevention & Level 5 = Camera Feed Bypass Prevention 
**ISO 30107-3** - Published: 2017- Purely Presentation Attack Detection Levels 1-3, no cybersecurity aspects or bypasses addressed.
**US Presidential Memorandum M-19-17** - “DHS is responsible for the following actions: 2. Lead research and development (R&D) coordination with the interagency, private sector, and international partner stakeholders to identify ICAM mission needs with related technology capability gaps, including in particular those that cannot be solved with currently fielded technologies and that may require additional R&D investment to reach operational deployment maturity…"
[NIST_800-63_RFI_FaceTec_Reply.pdf](https://github.com/usnistgov/800-63-4/files/6312256/NIST_800-63_RFI_FaceTec_Reply.pdf)

**Comment by JayMMeier** [comment]
### The impact of Liveness Detection or other Presentation Attack Detection capabilities on cost, usability, and market availability:
**Bias:** Liveness Detection hardware is expensive, largely proprietary, not interoperable, and limited in functionality and distribution. It can be economically biased against the less affluent. Liveness techniques that rely on camera sensors to capture reflected light from human skin are inherently biased against certain skin tones, age, and gender. Conversely, 3D software is inexpensive, and easy to deploy and maintain, while mitigating economic, skin, age, and gender biases. 
In-device Limitations: Most in-device liveness and biometrics, like Apple's Face ID and FIDO Authenticators, preclude server-side processing, limiting processing capability to that of the device processor, and limiting potential accuracy. They also cannot authenticate to a Subscriber Account or Issuer's root identity database for de-duplication and other anti-fraud strategies.
**Friction & Abandonment:**  Multimodal Liveness and matching tend to aggregate weak Liveness systems, dramatically increasing cost, session duration, user friction, and session abandonment. It doesn't significantly increase matching accuracy in most use cases. It further eliminates the opportunity for Liveness and match test concurrence, limiting potential confidence.
**Active vs. Passive:**  Active and Passive Liveness techniques are vulnerable to various and potentially different spoofing vectors. Passive Liveness looks for signs of “Deadness” and involuntary human Liveness signals, while Active Liveness primarily looks for the user to respond to a command for movement. Active Liveness systems increase friction and session abandonment and are more vulnerable to attack vectors like deep fake/video puppets or Imposter Attacks.
**3D vs. 2D:**  Three-dimensional (3D) Liveness approaches are able to capture orders-of-magnitude more data, increasing security confidence. They also are less reliant on light reflective or refractive techniques and are therefore naturally less biased toward skin tone, age, and gender. 2D systems are inherently less accurate than 3D, and vulnerable to perspective distortions related to variable capture distances.  
**Backward Compatibility:**  3D Liveness software approaches inherently collect orders-of-magnitude more biometric Liveness and Matching Data from the same 2D camera and are therefore significantly more backward compatible with old devices than 2D.   
**Honeypot Risk:**  Requiring the collection of 3D Facial Liveness and Matching data concurrently from the same video frame data feed can mitigate honeypot risk. By deleting some liveness data, not required for 3D matching after the initial Liveness check, the remaining 3D Face Matching Data, even if stolen and decrypted, cannot alone be re-submitted successfully. Yet, the 3D Matching Data can remain stored in the database for subsequent user authentications or account recovery. 
**Cost Reduction:**  3D software approaches also reduce cost significantly. They do not require specialized hardware, specific device brands, cameras, camera resolution, or operating systems. They can also utilize server-side matching and enrolled profile data, as well as server-side binary API responses.
[NIST_800-63_RFI_FaceTec_Reply.pdf](https://github.com/usnistgov/800-63-4/files/6312269/NIST_800-63_RFI_FaceTec_Reply.pdf)

**Comment by KantaraInitiative-IAWG** [comment]
Comment about "Liveness test for remote identity proofing #2":
The use of liveliness test and PAD is specifically focused on fraud detection and introduces significant friction to the ID proofing process. As such, this is only appropriate to make mandatory at IAL3. Below IAL3, it should be up to the agency to determine the appropriateness for their process and risk appetite.

**Comment by sschucke** [comment]
These are some thoughts as a member of the FIDO committee considering a certification program for remote identity proofing.  The development is ongoing.

(1) FIDO is in the process of developing a certification program for remote identity proofing that includes presentation attack detection as part of the testing.  The certification program for PAD will be based on ISO 30107-3 and other relevant, existing standards.
 
(2) FIDO has an existing Biometric Component Certification program for FIDO Authenticators, also based on 30107-3.  In the FIDO, PAD testing is a triaged approach based on three tiers as is described in detail in: 
https://fidoalliance.org/specs/biometric/requirements/#TriagePAD
and based on
https://pages.nist.gov/SOFA/SOFA.html
https://www.beat-eu.org/project/deliverables-public/d6-5-toward-common-criteria-evaluations-of-biometric-systems
 
(3) As we develop PAD testing for identity proofing, the framework for FIDO’s existing biometric certification program will adopted and updated based on threats for identity proofing (rather than authentication). In particular, since most remote identity proofing systems are based on face, face PAD framework will be developed, e.g.,
https://fidoalliance.org/specs/biometric/requirements/#PAISpeciesFace
 
(4) Presentation attacks, as defined in ISO 30107, are by definition focused on attacks on the biometric capture sub-system.  Other attacks, such as bypassing a camera/injection attacks, are considered security threats, not presentation attacks.  The FIDO committee is considering requirements to mitigate this and other attack vectors as part of a future certification program.  

(5) A stolen biometric characteristic or deepfake can be used to create a presentation attack, for example, displaying a face image on a computer monitor and presenting it as real face to the facial biometric capture system.  Alternatively, a stolen biometric characteristic or deepfake can be used by an attacker to digitally bypass the camera, through malware or other security vulnerability, commonly called an injection attack.   Identity proofing systems should protect from these and other types of security threats.

**Comment by tpriopka** [comment]
With respect to deepfakes, as Stephanie points out, they can either be used to attack a biometric capture sub-system (in a presentation attack), or they can be used in an injection attack (as a security threat). To this point, I would submit that explicit detection of deepfakes is not relevant to liveness detection. I say "explicit" because although they can be used to create presentation attacks, a deepfake does not need to be detected as such in order to be flagged in a presentation attack. In other words, a liveness test does not actually need to know (and should not have to know) about deepfakes at all. On the other hand, if the goal is to bullet proof the internal (post capture) security of an existing system, then deepfake detection could certainly be one component of such a system. The corollary to this is that deepfake detection per se is out of scope for liveness.

**Comment by JayMMeier** [comment]
> With respect to deepfakes, as Stephanie points out, they can either be used to attack a biometric capture sub-system (in a presentation attack), or they can be used in an injection attack (as a security threat). To this point, I would agree that explicit detection of deepfakes is not relevant to liveness detection. I say "explicit" because although they can be used to create presentation attacks, a deepfake does not need to be detected as such in order to be flagged in a presentation attack. In other words, a liveness test does not actually need to know (and should not have to know) about deepfakes at all. On the other hand, if the goal is to bullet proof the internal (post capture) security of an existing system, then deepfake detection could certainly be one component of such a system. The corollary to this is that deepfake detection per se is out of scope for liveness.

We might disagree with this view.  While a human face is, both 3D and alive, a 3D mask, while 3D, is not alive.  Conversely, proving two-dimensionality does prove the subject is not alive.  Thus, three-dimensionality should be a critical component of face-based liveness systems specifically relating to deep fakes, as well as other attacks.

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.
