### ISSUE TITLE
Redefinition of verifier impersonation resistance

### ISSUE THREAD

**Issue by jricher** [usnistgov/800-63-4#5]
At the time that SP 800-63B was written, Token Binding (RFC 8471-8473) was approaching standardization and was a promising method for providing phishing resistance, referred to in SP 800-63B as verifier impersonation resistance. Token binding would ensure that a single end-to-end TLS session has been established between endpoints, in this case between the claimant and the verifier.

Subsequently, vendors have abandoned their plans to implement token binding in web browsers. One reason cited for this is that some enterprises, for compliance reasons, require their clients to install root certificates allowing the enterprise to inspect client traffic. There is a need for an alternative set of requirements that promote phishing (verifier impersonation) resistance that is compatible with the current capabilities of modern web browsers.

NIST is seeking alternative requirements to take the place of token binding at AAL3. A primary candidate is to establish a binding between the authenticated server for a TLS connection and the key or keypair used for authentication. Any alternative requirements proposed should address much the same class of attacks (e.g., phishing) as addressed by token binding.

**Comment by The-FIDO-Alliance** [comment]
Verifier Impersonation Resistance is important as many existing attacks are phishing or real-time MITM attacks these days.  Those attacks demonstrate the weaknesses of legacy 2FA methods, such as HW-OTP or SMS-OTP.

Often, the root cause is that users are not doing a good job in differentiating phishing sites from legitimate web sites - and accidentally provide bearer tokens to the MITM attacker. This weakness needs to be addressed by the authentication protocol.

There are multiple ways how legitimate web sites could be distinguished from phishing sites. 

In terms of attacks, we see 4 general categories here, presented in order from least sophisticated to most sophisticated:  

1. Homograph attacks 
2. Confusing server names
3. Fraudulently issued TLS Server Certificates
4. Stolen TLS keys
 
Homograph attacks and using confusing server names (or paths) is the easiest for attackers. These attacks rely on a semantic confusion which is difficult to detect automatically.

The FIDO protocols bind public key credentials to Web Origins.  The FIDO Client automatically differentiates Web Origins and instructs the FIDO Authenticator to select the appropriate credential. More specifically, the FIDO Client will select the rp.com credential when communicating with the rp.com site presenting an accepted TLS server certificate for rp.com.  A phishing site (mitm.com) will be classified as different Web Origin, even if the URLs look similar (e.g. homograph attacks, confusing server names, etc.).  As a result, the FIDO protocol already protects against the attack types 1 and 2.

There have been occurrences of fraudulently issued TLS server certificates by some Certificate Authorities.  This attack is especially bad for relying parties as they haven’t done anything wrong. The attack is even possible if the relying party implements perfect security. A system called Certificate Transparency was introduced to detect such attacks, see https://certificate.transparency.dev/howctworks/.  Many User Agents support it.  With this method in place, running such an attack became more difficult.

Stealing TLS server private keys is another potential approach. It is more difficult as the relying party itself can implement countermeasures and even change certificates and private keys if such an attack is suspected.

The FIDO UAF protocol supports multiple “Channel binding” methods (e.g. RFC 5929 and RFC 8471).  The FIDO2/WebAuthn protocol supports RFC 8471.  The RFC 5929 and RFC 8471 based channel binding methods protect against fraudulently issued TLS server certificates.  The RFC 8471 also protects against situations in which the TLS server certificate and private key have been stolen and being re-used by the MITM attacker.  With that level of protection, the RFC 8471 Token Binding is the strongest method, but comes with some implications that are not always practical.

Concrete proposal: 
•	Focus on protection against items 1 and 2 for AAL2+ (as noted in our comments on phishing resistance). 
•	Add requirement for protection against items 3 and 4 to AAL3, allowing relying parties to take other mitigations for protecting the TLS server key (than just token binding).

**Comment by ve7jtb** [comment]
Yubico thinks Audience Restricted Tokens, which are a required part of the CTAP2 specification and include a browser validated RPID in the token, is an interim solution until Token Binding or a functional equivalent is implemented by browsers. 

Audience restricting the FIDO authentication tokens/assertions stops all verifier impersonation attacks except mis-issued certificates and stolen private keys. In order to protect against mis-issued certificates and stolen private keys, audience restricted FIDO tokens will require some additional mitigation efforts byRelying Parties. This will thwart the majority of attacks at AAL3. 

Some additional mitigation efforts on behalf of Relying Parties would be needed around mis-issuance of certificates, and protecting private keys. In the future, we can get more complicated solutions, but we will need the browser vendors on board. Regardless, we should continue to monitor and pursue the capabilities of Token Binding as a long-term solution.

John Bradley (Yubico)

**Comment by jimfenton** [comment]
@The-FIDO-Alliance One concern with your proposal is that, since support for RFC 8471 is generally not being implemented by browser vendors, authenticators such as FIDO would not be usable at AAL3 in most situations. The only acceptable forms of authentication at AAL3 would use hardware-based authenticators such as PIV Cards. Is that your interpretation as well? What mitigations for protecting the TLS server keys do you have in mind?

**Comment by ve7jtb** [comment]
@jimfenton  Fido Authentication can happen in places other than the browser.
As an example, ssh authentication using fido is bound to the ssh session as long as unique challenges are used.   

I believe that RFC 8471 is supported in Windows 10 (if not in edge anymore, as it uses it's own TLS stack) and desktop authentications using Fido would be bound to the TLS session as currently required. 

If we are talking about Web browser authentication then it is true that attacks where the certificate private key is compromised or a certificate has been miss issued are not directly mitigated by WebAuthn in current browsers.  

My argument is that RP can and should use HSM to protect keys, and also use Certificate transparency logs to protect against miss issuance.

The compromise of TLS opens many other attacks against the RP.   The browser may load malicious JavaScrypt that can do almost anything to the session once it is established. 

Mutual TLS authentication with PIV has the same problem, in that if there is a certificate compromise the attacker can replace cached JS libraries in the browser and get access to the RP via the authenticated session.

I really wish RFC 8471 had been adopted but the browsers consider protecting the channel in that way not sufficient to stop a real attacker that has a compromised certificate.  

If the desire is to use FIPS certified FIDO2 authenticators at AAL3 in browsers then the requirement needs to focus on the main threats of Homograph attacks and 
Confusing server names by audience restricting the assertion/token as is currently done in WebAuthn.   Other methods need to be considered for protecting against Fraudulently issued TLS Server Certificates and Stolen server TLS keys.

John B.

**Comment by The-FIDO-Alliance** [comment]
Thanks Jim.  We agree that TokenBinding (RFC8471) is not widely supported by browsers today.

But we propose a slightly more differentiated definition of AAL3.  The main goal of AAL3 is the protection against MITM attacks.

There are different categories of MITM attacks (see https://github.com/usnistgov/800-63-4/issues/5#issuecomment-820685529).
Using FIDO authentication already protects against the above mentioned MITM categories 1 and 2.

FIDO UAF and FIDO2 can be used in native applications.  FIDO UAF already supports multiple “channel binding” methods (see https://fidoalliance.org/specs/fido-uaf-v1.2-ps-20201020/fido-uaf-protocol-v1.2-ps-20201020.html#tls-channelbinding-dictionary) – including RFC8471 but also according to RFC5929.  In native apps, it is often possible to use RFC8471 – even in conjunction with FIDO2.

With that, AAL3 can be reached – even with the current definition of AAL3.

It is unfortunate that most browsers don’t implement RFC8471 today. However most browsers do implement other countermeasures against the MITM category 3 & 4 attacks, e.g. certificate transparency and blacklists (https://chromium.googlesource.com/chromium/src/+/c77495f99003b06f5e9d6ac750b6ffb0afdb582a/net/data/ssl/blacklist/README.md).

Additionally, relying parties can implement additional mitigations against MITM category 4 attacks.

So we propose that NIST 800-63 v4 explicitly mentions these mitigations and allows relying parties to achieve AAL3 when implementing them.

We'd welcome the chance to talk more about this topic - we know it's a tricky one.

**Comment by jricher** [comment]
Thank you for the discussion. Public discussion on this issue is now closed.

NIST will publish a draft of revision 4 in the future. Upon publication, a public comment period on the draft of revision 4 will open.
